print("__#####__")
print("(*^^*)")
print("_0_0_")
print("파이썬사랑")
print("<(^..^)>")
print("('(00)')")
print()

print("__#####__\n  (*^^*) \n __0__0__\n파이썬사랑")
print()
print("<(^..^)>\n('(00)')")
print()